version: '3.9'

services:
  web:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: next-frontend
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/front
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn"

  server:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: go-backend
    tty: true
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - go-data:/go

  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: 'portfolio'
      POSTGRES_PASSWORD: 'Xshion0912'
      POSTGRES_USER: 'shion0625'
      TimeZone: Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data

volumes:
  go-data:
