name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Move to Frontend Directory
        run: cd frontend

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Run ESLint
        run:  yarn run eslint --format junit --output-file eslint-results.xml
        env:
          CI: true
        working-directory: ./frontend

      - name: Upload ESLint Results
        uses: actions/upload-artifact@v2
        with:
          name: eslint-results
          path: eslint-results.xml
