name: Prettier

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move to Frontend Directory
        run: cd frontend

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Run Prettier
        run: |
          yarn format
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A .
          git diff-index --quiet HEAD || git commit -m "Auto-format code with Prettier [skip ci]"
          git push origin ${GITHUB_REF#refs/}:${{ github.head_ref }}
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./frontend
